# -*- coding: utf-8 -*-
"""
中文到英文/拼音映射表
Global Code Optimization - Chinese to English/Pinyin Mappings
"""

# 中文到拼音/英文映射表
CHINESE_TO_PINGYIN = {
    # 通用词汇
    "记忆": "memory", "用户": "user", "输入": "input", "输出": "output",
    "状态": "status", "数据": "data", "信息": "info", "内容": "content",
    "类型": "type", "结果": "result", "成功": "success", "失败": "failure",
    "错误": "error", "警告": "warning", "调试": "debug", "请求": "request",
    "响应": "response", "处理": "process", "执行": "execute", "完成": "complete",
    "开始": "start", "停止": "stop", "重置": "reset", "初始化": "init",
    "配置": "config", "设置": "settings", "获取": "get", "更新": "update",
    "删除": "delete", "添加": "add", "创建": "create", "销毁": "destroy",
    "加载": "load", "保存": "save", "读取": "read", "写入": "write",
    "解析": "parse", "验证": "validate", "检查": "check", "分析": "analyze",
    "生成": "generate", "返回": "return",
    # 神经记忆相关
    "神经": "neural", "智能": "smart", "学习": "learning", "推理": "reasoning",
    "思维": "thinking", "思考": "thought", "认知": "cognitive", "感知": "perception",
    "决策": "decision", "策略": "strategy", "方案": "solution", "计划": "plan",
    "目标": "goal", "任务": "task", "工作": "work", "事件": "event",
    "动作": "action", "行为": "behavior", "效果": "effect", "反馈": "feedback",
    "强化": "reinforce", "奖励": "reward", "惩罚": "penalty", "价值": "value",
    "评估": "evaluate", "评分": "score", "排序": "rank", "优化": "optimize",
    "调整": "adjust", "适配": "adapt", "融合": "fusion", "整合": "integration",
    "合并": "merge", "同步": "sync", "异步": "async", "缓存": "cache",
    "存储": "storage", "数据库": "database", "文件": "file", "目录": "directory",
    "路径": "path", "文件夹": "folder", "序列": "sequence", "列表": "list",
    "字典": "dict", "映射": "mapping", "关联": "relation", "关系": "relationship",
    "连接": "connect", "断开": "disconnect", "会话": "session", "上下文": "context",
    "环境": "environment", "参数": "parameter", "属性": "property", "特性": "feature",
    "功能": "function", "模块": "module", "组件": "component", "服务": "service",
    "引擎": "engine", "核心": "core", "系统": "system", "架构": "architecture",
    "框架": "framework", "接口": "interface", "协议": "protocol", "标准": "standard",
    "规范": "specification", "版本": "version", "日志": "log", "记录": "record",
    "追踪": "trace", "监控": "monitor", "告警": "alert", "报告": "report",
    "统计": "statistics", "指标": "metric", "度量": "measure", "计数": "count",
    "时间": "time", "日期": "date", "时刻": "timestamp", "持续": "duration",
    "延迟": "latency", "超时": "timeout", "重试": "retry", "回退": "fallback",
    "降级": "degrade", "熔断": "circuit_break", "限流": "rate_limit",
    "并发": "concurrent", "并行": "parallel", "串行": "serial", "队列": "queue",
    "堆栈": "stack", "树形": "tree", "图形": "graph", "网络": "network",
    "节点": "node", "边": "edge", "权重": "weight", "阈值": "threshold",
    "容差": "tolerance", "精度": "precision", "准确率": "accuracy",
    "召回率": "recall", "F1": "f1_score", "概率": "probability",
    "置信度": "confidence", "样本": "sample", "批次": "batch", "流": "stream",
    "批处理": "batch_process", "实时": "realtime", "离线": "offline",
    "在线": "online", "本地": "local", "远程": "remote", "云端": "cloud",
    "边缘": "edge", "服务器": "server", "客户端": "client", "终端": "terminal",
    "设备": "device", "硬件": "hardware", "软件": "software", "内存": "memory",
    "磁盘": "disk", "线程": "thread", "进程": "process", "协程": "coroutine",
    "锁": "lock", "信号": "signal", "异常": "exception", "捕获": "capture",
    "抛出": "throw", "恢复": "recover", "回滚": "rollback", "提交": "commit",
    "事务": "transaction", "原子性": "atomicity", "一致性": "consistency",
    "隔离性": "isolation", "持久性": "durability",
    # 领域词汇
    "智慧": "wisdom", "哲学": "philosophy", "儒": "confucian", "道": "dao",
    "佛": "buddhist", "兵法": "military", "谋略": "tactics", "管理": "management",
    "领导": "leadership", "沟通": "communication", "协作": "collaboration",
    "团队": "team", "个人": "individual", "组织": "organization", "文化": "culture",
    "传统": "tradition", "现代": "modern", "增长": "growth", "营销": "marketing",
    "销售": "sales", "客户": "customer", "产品": "product", "品牌": "brand",
    "市场": "market", "行业": "industry", "竞争": "competition", "优势": "advantage",
    "劣势": "disadvantage", "机会": "opportunity", "威胁": "threat",
    "SWOT": "swot", "战略": "strategic", "战术": "tactical", "落地": "implementation",
    "迭代": "iteration", "循环": "cycle", "螺旋": "spiral", "趋势": "trend",
    "预测": "prediction", "预期": "expectation", "实际": "actual", "预算": "budget",
    "成本": "cost", "收益": "revenue", "利润": "profit", "亏损": "loss",
    "投资": "investment", "回报": "return", "ROI": "roi", "效率": "efficiency",
    "效果": "effectiveness", "质量": "quality", "数量": "quantity", "规模": "scale",
    "范围": "scope", "优先级": "priority", "重要性": "importance", "紧急度": "urgency",
    "风险": "risk", "安全": "security", "隐私": "privacy", "合规": "compliance",
    "法律": "legal", "伦理": "ethics", "道德": "moral", "责任": "responsibility",
    "权利": "right", "义务": "obligation", "自由": "freedom", "约束": "constraint",
    "限制": "limitation", "禁止": "prohibition", "允许": "permission",
    "要求": "requirement", "需要": "need", "想要": "want", "必须": "must",
    "应该": "should", "选择": "choice", "决定": "decision", "判断": "judgment",
    "评价": "evaluation", "比较": "comparison", "对比": "contrast",
    "综合": "synthesis", "总结": "summary", "概括": "summarize", "归纳": "induction",
    "演绎": "deduction", "推论": "inference", "假设": "hypothesis",
    "理论": "theory", "模型": "model", "范式": "paradigm", "模式": "pattern",
    "模板": "template", "案例": "case", "实例": "instance", "示例": "sample",
    "演示": "demo", "原型": "prototype", "迁移": "migration", "转换": "conversion",
    "导入": "import", "导出": "export", "备份": "backup", "恢复": "restore",
    "归档": "archive", "压缩": "compression", "解压": "decompression",
    "加密": "encryption", "解密": "decryption", "签名": "signature",
    "验证": "verification", "认证": "authentication", "授权": "authorization",
    "权限": "permission", "角色": "role", "管理员": "admin", "访客": "guest",
    "订阅": "subscribe", "发布": "publish", "订阅者": "subscriber",
    "发布者": "publisher", "生产者": "producer", "消费者": "consumer",
    "消息": "message", "通知": "notification", "提醒": "reminder",
    "确认": "confirmation", "取消": "cancellation", "拒绝": "rejection",
    "接受": "acceptance", "批准": "approval", "驳回": "rejection",
    "同意": "agreement", "不同意": "disagreement", "中立": "neutral",
    "积极": "positive", "消极": "negative", "支持": "support", "反对": "oppose",
    "投票": "vote", "选举": "election", "任命": "appointment", "招聘": "recruitment",
    "解雇": "dismissal", "晋升": "promotion", "降职": "demotion", "调动": "transfer",
    "辞职": "resignation", "退休": "retirement", "培训": "training",
    "发展": "development", "成长": "growth", "教育": "education",
    "教学": "teaching", "指导": "guidance", "辅导": "coaching", "咨询": "consulting",
    "建议": "advice", "推荐": "recommendation", "提示": "tip", "技巧": "technique",
    "方法": "method", "方式": "way", "手段": "means", "途径": "approach",
    "渠道": "channel", "路线": "route", "方向": "direction", "目的": "purpose",
    "意图": "intent", "动机": "motivation", "原因": "cause", "结果": "consequence",
    "影响": "impact", "作用": "effect", "用途": "use", "应用": "application",
    "利用": "utilization", "浪费": "waste", "节省": "saving", "节约": "conservation",
    "消耗": "consumption", "生产": "production", "制造": "manufacturing",
    "创造": "creation", "创新": "innovation", "发明": "invention", "发现": "discovery",
    "探索": "exploration", "研究": "research", "调查": "investigation",
    "审查": "review", "审计": "audit", "检验": "inspection", "测试": "testing",
    "试验": "trial", "实验": "experiment", "证明": "proof", "证据": "evidence",
    "事实": "fact", "知识": "knowledge", "洞察": "insight", "理解": "understanding",
    "认识": "recognition", "感觉": "sensation", "直觉": "intuition",
    "灵感": "inspiration", "创意": "creativity", "想象": "imagination",
    "幻想": "fantasy", "梦想": "dream", "愿景": "vision", "使命": "mission",
    "价值观": "value", "信念": "belief", "信仰": "faith", "原则": "principle",
    "准则": "standard", "规则": "rule", "法规": "regulation", "政策": "policy",
    "制度": "institution", "体制": "system", "机制": "mechanism", "流程": "process",
    "程序": "procedure", "步骤": "step", "时期": "period", "时代": "era",
    "年代": "decade", "世纪": "century", "年": "year", "月": "month", "周": "week",
    "日": "day", "小时": "hour", "分钟": "minute", "秒": "second",
    "过去": "past", "将来": "future", "未来": "future", "历史": "history",
    "当代": "contemporary", "古代": "ancient", "远古": "ancient", "史前": "prehistoric",
    "预期": "expected", "估计": "estimated", "估算": "approximated",
    "计算": "calculated", "测量": "measured", "实验": "experimented",
    "确认": "confirmed", "反驳": "refuted", "否定": "negated", "承认": "admitted",
    "坦白": "confessed", "隐瞒": "concealed", "揭露": "exposed", "公开": "public",
    "秘密": "secret", "机密": "confidential", "透明": "transparent", "清晰": "clear",
    "模糊": "vague", "明确": "explicit", "隐含": "implicit", "直接": "direct",
    "间接": "indirect", "具体": "specific", "抽象": "abstract", "详细": "detailed",
    "简要": "brief", "简洁": "concise", "冗长": "verbose", "精炼": "refined",
    "完整": "complete", "不完整": "incomplete", "全面": "comprehensive",
    "片面": "one-sided", "客观": "objective", "主观": "subjective", "偏见": "biased",
    "公平": "fair", "不公平": "unfair", "合理": "reasonable", "不合理": "unreasonable",
    "理性": "rational", "感性": "emotional", "逻辑": "logical", "非逻辑": "illogical",
    "随机": "random", "有序": "ordered", "混乱": "chaotic", "稳定": "stable",
    "不稳定": "unstable", "动态": "dynamic", "静态": "static", "变化": "change",
    "不变": "unchanged", "停滞": "stagnation", "进步": "progress", "退步": "regression",
    "衰退": "decline", "繁荣": "prosperity", "危机": "crisis", "机遇": "opportunity",
    "挑战": "challenge", "困难": "difficulty", "简单": "simple", "复杂": "complex",
    "容易": "easy", "可行": "feasible", "不可行": "infeasible", "可能": "possible",
    "不可能": "impossible", "必然": "inevitable", "偶然": "accidental",
    "确定": "certain", "不确定": "uncertain", "肯定": "definite", "否定": "indefinite",
    "绝对": "absolute", "相对": "relative", "普遍": "universal", "特殊": "special",
    "一般": "general", "个别": "particular", "典型": "typical", "异常": "abnormal",
    "正常": "normal", "规范": "standardized", "合法": "legal", "非法": "illegal",
    "违规": "non-compliant", "可选": "optional", "必要": "necessary",
    "不重要": "unimportant", "紧急": "urgent", "次要": "secondary", "主要": "primary",
    "外围": "peripheral", "内部": "internal", "外部": "external", "表面": "surface",
    "深层": "deep", "浅层": "shallow", "局部": "local", "全局": "global",
    "整体": "whole", "个体": "individual", "集体": "collective", "公共": "public",
    "私人": "private", "共享": "shared", "独占": "exclusive", "封闭": "closed",
    "免费": "free", "付费": "paid", "商业": "commercial", "非商业": "non-commercial",
    "盈利": "profitable", "非盈利": "non-profit", "独立": "independent",
    "依赖": "dependent", "自主": "autonomous", "受控": "controlled",
    "主动": "proactive", "被动": "reactive", "正面": "positive", "负面": "negative",
    "建设性": "constructive", "破坏性": "destructive", "有益": "beneficial",
    "有害": "harmful", "有利": "favorable", "不利": "unfavorable", "高效": "efficient",
    "低效": "inefficient", "生产力": "productive", "投入": "input", "产出": "output",
    "资源": "resource", "资产": "asset", "负债": "liability", "资本": "capital",
    "资金": "fund", "现金": "cash", "支出": "expense", "费用": "fee",
    "价格": "price", "价值": "value", "比率": "ratio", "比例": "proportion",
    "百分比": "percentage", "可能性": "likelihood", "减少": "decrease",
    "增加": "increase", "降低": "reduce", "恶化": "worsen", "改善": "improve",
    "变坏": "deteriorate", "保持": "maintain", "修改": "modify", "改进": "enhance",
    "完善": "perfect", "修复": "fix", "纠正": "correct", "补救": "remedy",
    "预防": "prevent", "治疗": "treat", "治愈": "cure", "保护": "protect",
    "损害": "damage", "伤害": "harm", "破坏": "destroy", "建设": "build",
    "摧毁": "demolish", "移除": "remove", "插入": "insert", "提取": "extract",
    "复制": "copy", "移动": "move", "重命名": "rename", "交换": "swap",
    "分离": "separate", "分解": "decompose", "分离": "segregate", "锁定": "lock",
    "解锁": "unlock", "启用": "enable", "禁用": "disable", "激活": "activate",
    "停用": "deactivate", "暂停": "pause", "继续": "resume", "终止": "terminate",
    "中断": "interrupt", "跳过": "skip", "放弃": "abandon", "坚持": "persist",
    "前进": "advance", "后退": "retreat", "上升": "ascend", "下降": "descend",
    "到达": "arrive", "离开": "depart", "加入": "join", "抵达": "reach",
    "访问": "access", "浏览": "browse", "搜索": "search", "查找": "find",
    "分配": "allocate", "分发": "distribute", "收集": "collect", "聚集": "gather",
    "积累": "accumulate", "储存": "store", "保留": "retain", "丢弃": "discard",
    "清除": "clear", "清理": "clean", "整理": "organize", "分类": "classify",
    "排列": "arrange", "协调": "coordinate", "控制": "control", "监督": "supervise",
    "指挥": "command", "支配": "dominate", "说服": "persuade", "劝告": "advise",
    "告知": "inform", "关注": "pay_attention", "考虑": "consider", "记住": "remember",
    "忘记": "forget", "回忆": "recall", "推测": "speculate", "猜想": "guess",
    "预言": "prophesy", "预报": "forecast", "预告": "foretell", "期待": "expect",
    "希望": "hope", "渴望": "desire", "能够": "be_able_to", "不必": "need_not",
    "不能": "cannot", "不会": "will_not", "不愿": "be_unwilling", "不敢": "dare_not",
    "不要": "do_not", "谢谢": "thank_you", "对不起": "sorry", "抱歉": "apologies",
    "没关系": "never_mind", "请多指教": "please_give_advice", "多多关照": "please_take_care",
    "不胜荣幸": "honored", "幸会": "nice_to_meet_you", "久仰": "long_admired",
    "拜访": "visit", "会见": "meet", "会面": "meet", "会议": "conference",
    "会谈": "talks", "商量": "discuss", "商议": "negotiate", "辩论": "debate",
    "争论": "argue", "争吵": "quarrel", "争执": "dispute", "矛盾": "conflict",
    "冲突": "conflict", "麻烦": "trouble", "障碍": "obstacle", "难题": "puzzle",
    "疑问": "question", "困惑": "confusion", "不明白": "not_understand",
    "不理解": "not_comprehend", "不确定": "uncertain", "无": "none", "有": "have",
    "对": "correct", "错": "wrong", "真": "true", "假": "false",
    "优": "excellent", "劣": "inferior", "多": "many", "少": "few",
    "每个": "every", "一些": "some", "任何": "any", "所有": "all",
    "和": "and", "或": "or", "但": "but", "而": "however", "所以": "therefore",
    "因为": "because", "如果": "if", "虽然": "although", "即使": "even_if",
    "只要": "as_long_as", "除非": "unless", "除了": "except", "关于": "about",
    "对于": "for", "通过": "through", "由于": "due_to", "根据": "according_to",
    "按照": "in_accordance_with", "依据": "based_on", "基于": "based_on",
    "鉴于": "in_view_of", "涉及": "involving", "包括": "including",
    "此外": "furthermore", "并且": "moreover", "于是": "then", "因此": "thus",
    "故": "hence", "从而": "so_as_to", "以致": "resulting_in", "直到": "until",
    "自从": "since", "目前": "currently", "当前": "presently", "如今": "nowadays",
    "届时": "at_that_time", "先前": "previously", "将要": "will", "准备": "about_to",
    "打算": "intend_to", "计划": "plan_to", "试图": "attempt_to", "尝试": "try_to",
    "努力": "strive_to", "设法": "manage_to", "也许": "perhaps", "大概": "probably",
    "似乎": "seem", "好像": "as_if", "看来": "it_seems", "感觉": "feel",
    "觉得": "think", "认为": "think", "相信": "believe", "怀疑": "doubt",
    "清楚": "clear", "明白": "understand", "懂": "understand", "知道": "know",
    "了解": "know", "熟悉": "be_familiar_with", "掌握": "master",
    "精通": "be_proficient_in", "擅长": "be_good_at", "专长": "expertise",
    "专业": "professional", "职业": "occupation", "职务": "position",
    "职位": "post", "身份": "identity", "地位": "status", "等级": "level",
    "级别": "rank", "层次": "tier", "环节": "link", "工序": "operation",
    "活动": "activity", "实践": "practice", "用途": "use", "效益": "benefit",
    "好处": "advantage", "缺点": "drawback", "不足": "shortcoming",
    "弱点": "weakness", "强项": "strength", "长处": "strength", "优点": "merit",
    "美德": "virtue", "品质": "quality", "特点": "characteristic", "属性": "property",
    "性质": "nature", "本质": "essence", "要点": "point", "重点": "emphasis",
    "焦点": "focus", "中心": "center", "主题": "topic", "话题": "subject",
    "题目": "title", "材料": "material", "素材": "source_material", "档案": "archive",
    "摘要": "abstract", "预览": "preview", "大纲": "outline", "草稿": "draft",
    "初稿": "first_draft", "定稿": "final_draft", "文稿": "manuscript",
    "稿件": "contribution", "文章": "article", "论文": "thesis", "著作": "work",
    "作品": "work", "改良": "reform", "改革": "reform", "革命": "revolution",
    "变革": "transformation", "转变": "transformation", "转型": "restructuring",
    "过渡": "transition", "演变": "evolution", "退化": "degeneration",
    "衰落": "decline", "没落": "decline", "兴盛": "prosperity", "兴旺": "thrive",
    "发达": "developed", "发展中": "developing", "落后": "backward", "先进": "advanced",
    "中世纪": "medieval", "近代": "modern", "当代": "present", "永久": "permanent",
    "暂时": "temporary", "长期": "long_term", "短期": "short_term",
    "中期": "medium_term", "临时": "temporary", "经常": "frequently",
    "偶尔": "occasionally", "有时": "sometimes", "常常": "often", "总是": "always",
    "从不": "never", "从未": "never", "尚未": "not_yet", "即将": "about_to",
    "还": "still", "仍然": "still", "要": "want_to", "想": "want",
    "莫": "do_not", "勿": "do_not", "休": "stop", "止": "stop",
}

# 中文标点符号到英文标点符号映射
CHINESE_PUNCT_TO_ASCII = {
    '「': '"', '」': '"', '『': "'", '』': "'",
    '【': '[', '】': ']', '（': '(', '）': ')',
    '《': '<', '》': '>', '〈': '<', '〉': '>',
    '！': '!', '？': '?', '。': '.', '，': ',',
    '；': ';', '：': ':', '、': ',',
    '"': '"', '"': '"', ''': "'", ''': "'",
    '～': '~', '·': '·', '……': '...', '…': '...',
    '—': '-', '–': '-', '“': '"', '”': '"',
    '‖': '|', '｜': '|', '＋': '+', '－': '-',
    '＝': '=', '×': '*', '÷': '/', '％': '%',
    '￥': '$', '€': 'EUR', '£': 'GBP', '•': '*',
}
